### ISSUE TITLE
Can't login for edits from web interface

### ISSUE THREAD

**Issue by harisont** [GrammaticalFramework/gf-wordnet#29]
I've tried to make some adjustments to Italian words from the web interface but for the past couple of days I've been unable to log in, even though I had had no issues in the past.

**Comment by krangelov** [comment]
I have been getting warnings from GitHub that the way that I use for
authentication will be deprecated and I need to change something. Probably
they finally disabled it. I will fix it but in the meantime you can use an
ordinary commit.

**Comment by krangelov** [comment]
It works again!
