### ISSUE TITLE
Russian

### ISSUE THREAD

**Issue by harisont** [GrammaticalFramework/gf-wordnet#31]
Hi! 

Would it be possible to add Russian in the very near future, and if so how long would that take approximately? Or how could I do it myself?

I'm trying to adapt some GF-based grammar exercises to Russian for [this beginner Swedish course directed to Ukrainian refugees](https://github.com/elenavolodina/SwedishFromScratch) and the GF Wordnet would make everything much easier.

**Comment by harisont** [comment]
Thank you! 
As I was saying yesterday, I will try to take a look at this after a first version of the program for the exercises is up and running.

**Comment by krangelov** [comment]
Now there is a Russian WordNet. I checked a few hundred items and the quality is pretty good. Of course there are mistakes as well. I guess it helps a lot that the algorithms can use Bulgarian as a pivot language.
