### ISSUE TITLE
Best way to "install" and use gf-wordnet

### ISSUE THREAD

**Issue by kristiank** [GrammaticalFramework/gf-wordnet#33]
This project has nice documentation and pointer to other resources and projects, but for a complete beginner, there is a lack of a "getting started" section.

What is the preferred place to keep the gf-wordnet files? There seem to be many possibilities and it's hard to choose between them. One option seems to keep the gf-wordnet folder under `/usr/local/share/gf-rgl/gf-wordnet`.

**Comment by krangelov** [comment]
The answer depends on how you want to use the resource:

- If you want to use it as a resource similar to how the RGL is used, then do "make; make install". This will install all WordNet???.gfo files in the same folder in which the RGL is installed. Then you can import the modules as any other.

- If you want to use the resource directly for parsing or linearization, then after doing "make" you will get Parse.pgf in the main folder. This contains the WordNet plus an extended version of the RGL syntax.

Systematic "getting started" section would be a good idea.

**Comment by inariksit** [comment]
Regarding the Makefile, it uses this path

```
INSTALL_PATH=$(GF_LIB_PATH)/lib
```

Personally, my GF_LIB_PATH is the following—it became that when I installed the RGL using the `DATA_DIR` method back when I had GF 3.10.3., and then I just froze that path into `GF_LIB_PATH` variable. 

```
/Users/inari/work/GF/gf-core/.stack-work/install/x86_64-osx/eba2bfc6d5a44bdfc97d07f36908bd11f9f093a0a68d5123d58d85b7f931a5b9/8.2.2/share/x86_64-osx-ghc-8.2.2/gf-3.10.3/lib
```

If I use `make install`, it puts the files in a directory called `/Users/inari/…/gf-3.10.3/lib/lib`. 
* Is this your intention, that GF_LIB_PATH would contain directories `alltenses`, `present`, `prelude` and `lib`?
* Or is my GF_LIB_PATH nonstandard and you intended the WordNet files to be direct neighbours of the `alltenses` etc. directories?

**Comment by krangelov** [comment]
The intention is to put the .gfo files directly in the GF_LIB_PATH along
with alltenses, present, etc. This means that this line in the Makefile is
wrong:

INSTALL_PATH=$(GF_LIB_PATH)/lib

I never actually used it with a custom GF_LIB_PATH.

**Comment by kristiank** [comment]
I have one more question before closing this issue. How can I specify which languages I want to "install"? I understand I can change the Makefile, but I guess this is not preferable. Can I give it via some command line parameter or flag? Thank you.
