### ISSUE TITLE
Web interface broken

### ISSUE THREAD

**Issue by kristiank** [GrammaticalFramework/gf-wordnet#34]
I wanted to correct some Estonian words. I pressed Log in and signed in to GitHub, after redirection I get this:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/1181113/174291740-aca6542a-02e0-4146-b9dd-6a470d465d7a.png">
After refreshing it shows this:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/1181113/174291833-d5c98d3f-9adb-4d7d-987c-1151bd53eee3.png">

**Comment by krangelov** [comment]
I think you need to be a collaborator to the repository to have access to the login. I sent you an invitation. Please let me know if this solves the issue. Obviously there should be a better error message if this is the case.

**Comment by kristiank** [comment]
No, it doesn't work via the web interface. But I was able to push a commit straight to the repository from my command line.

**Comment by krangelov** [comment]
It doesn't work even after I added you as a contributor?

No problem to push directly, just make a fresh clone before your next push.
See my other e-mail that I sent to you today.
