### ISSUE TITLE
Postmortem question

### ISSUE THREAD

**Issue by kiufta** [GrammaticalFramework/gf-wordnet#36]
Hi Krasimir,

why has http://wordnet-rdf.princeton.edu/id/01414776-a become http://wordnet-rdf.princeton.edu/id/14014160-n ?

I've seen your edit at Wikidata ;)

**Comment by krangelov** [comment]
Because I think the new sense represents better Q628939. In general the
Wikidata items are linguistically represented better by nouns, having an
adjective looks odd. On the other hand we have guilt and guilty which are
connected in WordNet but I don't see how to make that connection in
Wikidata.
