### ISSUE TITLE
Parse example in the Python README.md

### ISSUE THREAD

**Issue by stephanemagnenat** [GrammaticalFramework/gf-wordnet#50]
I think that it would be most helpful for beginner users to have an example on how to use the parse function in the `python/README.md` (and maybe a helper in `_api.py` to access this function if that would be helpful).

That way, users could very easily explore the round trip from parsing to expression to linearization.

**Comment by krangelov** [comment]
The GF runtume from the master branch supports parsing, but the WordNet relies on an alternative branch which doesn't have a parser yet. Actually there is something but it is not ready for serious use yet.

**Comment by stephanemagnenat** [comment]
Ah, I see, thank you for the explanation.

Is there a roadmap or an estimation regarding when WordNet would get parsing? I am asking as I am considering using GF and its WordNet integration to do software localization, and as we are not linguists I would imagine to have a tool that takes our existing string keys, which are in English, and that proposes the various valid interlingua expressions for us to choose from.

That would also allow us to estimate the feasibility of that approach in the first place, by feeding all our existing string keys and measuring statistics such as the number of failed parsing, the quality of the linearization in languages we speak, etc.
