### ISSUE TITLE
In Python, German and French downloads fail

### ISSUE THREAD

**Issue by stephanemagnenat** [GrammaticalFramework/gf-wordnet#51]
Following the instruction of the Python README, the following works for English:
```python
>>> wordnet.download(['eng'])
Download and boot the grammar 355MB (Expanded to 2719MB)
Download the semantics database 2814MB done
Reload wordnet
```

but fails for French and German:
```python
wordnet.download(['fra'])
Download and boot the grammar 138MBTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/steph/.local/lib/python3.10/site-packages/wordnet/__init__.py", line 54, in download
    pgf.bootNGF(readinto, path+"Parse.ngf")
pgf.PGFError: reached end of file while reading the grammar
```

I am using Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux, on Ubuntu 22.04.1, with wordnet installed using pip3 as explained in the README.

**Comment by krangelov** [comment]
We use 'fre' for French and 'ger' for German

**Comment by stephanemagnenat** [comment]
Thank you for the answer! I got confused because the README talks about using "ISO 639‑2" and I did not realize these had two codes and here the "bibliographic" is used. Maybe in term of user experience, a feature wish could be that the user-facing API could accept both?
