### ISSUE TITLE
python-webkit not maintained

### ISSUE THREAD

**Issue by odanoburu** [GrammaticalFramework/gf-wordnet#6]
mirroring https://github.com/andresriancho/w3af/issues/13635.

this package is no longer maintained and has been dropped from the latest Ubuntu and Debian releases, so the `wordnet-ide` cannot run straightforwardly in these platforms.

I imagine this is low priority, so alternatives I can think of are compiling from source (instructions [here](http://www.gnu.org/software/pythonwebkit/)) or downgrading.

**Comment by krangelov** [comment]
Replaced with an online interface
